version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - "3000:80"
    volumes:
      - ./build:/usr/share/nginx/html
    restart: always

